const items = [
    'carrot',
    'broccoli',
    'asparagus',
    'cauliflower',
    'corn',
    'cucumber',
    'green pepper',
    'lettuce',
   ' mushrooms',
    'onion',
    'potato',
    'pumpkin',
    'red pepper',
    'tomato',
    'beetroot',
    'brussel sprouts',
    'peas',
    'zucchini',
    'radish',
    'sweet potato',
    'artichoke',
    'leek',
    'cabbag',
    'celery',
    'chili',
    'garlic',
    'basil',
    'coriander',
    'parsley',
    'dill',
    'rosemary',
    'oregano',
    'cinnamon',
    'saffron',
    'green bean',
    'bean',
    'chickpea',
    'lentil',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'blackberry',
    'blackcurrant',
    'blueberry',
    'boysenberry',
    'cherry',
    'coconut',
    'fig',
    'grape',
    'grapefruit',
    'kiwifruit',
    'lemon',
    'lime',
    'lychee',
    'mandarin',
    'mango',
    'melon',
    'nectarine',
    'orange',
    'papaya',
    'passion fruit',
    'peach',
    'pear',
]